version: '3'

services:
  spring-petclinic:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
    depends_on:
      - mysql

  spring-petclinic-rest:
    image: springcommunity/spring-petclinic-rest
    ports:
      - "9966:9966"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: