version: '3'
services:
  spring-petclinic-rest:
    image: springcommunity/spring-petclinic-rest
    ports:
      - "9966:9966"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-petclinic:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
    depends_on:
      - mysql-petclinic

  spring-petclinic:
    image: springcommunity/spring-framework-petclinic
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-petclinic:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
    depends_on:
      - mysql-petclinic

  mysql-petclinic:
    image: mysql:8.0
    environment:
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
